{% set name = "flake8-use-fstring" %}
{% set version = "1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-use-fstring-{{ version }}.tar.gz
  sha256: aa3ac530f4a6192ab5883e3c07248ba4e95338cea8f6ab7c1b7868bf89759f99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flake8 >=3
    - python >=3.6

test:
  imports:
    - flake8_use_fstring
  commands:
    - pip check
    - flake8 --version | grep use-fstring
  requires:
    - pip

about:
  home: https://github.com/MichaelKim0407/flake8-use-fstring
  summary: Flake8 plugin for string formatting style.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
